remote_theme: jekyll/minima

title: xarantolus
author:
  name: xarantolus
  email: x@010.one
description: ""

show_excerpts: true 

permalink: :title

url: https://xarantolus.github.io
baseurl: /

minima:
  date_format: "%Y-%m-%d"
  skin: dark

  # generate social links in footer
  #social_links:
    # github:  xarantolus
    # devto: jekyll

header_pages: [""]

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-relative-links
